#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryusei Fujimura　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys
 

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)


ans = 2
for line in sys.stdin:
    line = line.rstrip()
    if line.isdecimal() == True:
        ans = ans ** tonum(line)
    else:
        print("整数を入力してください")
        sys.exit()

print(ans)
