#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryusei Fujimura
# mailaddress: s23c1125ja@s.chibakoudai.jp　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys
 

def tonum(s):
    try:
        return int(s)
    except:
        return float(0)


ans = 2
for line in sys.stdin:
    line = line.rstrip()
    if line.isdecimal() == True:
        ans = ans ** tonum(line)
    else:
        print("整数以外を感知しました")
        sys.exit()

print(ans)
